@echo off
rem можно пояснить, что полные пути не есть хорошо, и показать, как помогают PATH, JAVA_HOME и относительные URL...
"C:\Program Files\Java\jdk-11.0.6\bin\java" -cp .;..\..\out\production\Seminar_2 Test
